// <auto-generated />
namespace DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class EdittedUserIdfromToken : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EdittedUserIdfromToken));
        
        string IMigrationMetadata.Id
        {
            get { return "202510291729005_Editted UserId from Token"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
